#!/system/bin/sh


busybox echo "CPU Information"
busybox echo "available governor:"
busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
busybox echo "governor:"
busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor
busybox echo "available freq:"
busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_frequencies
busybox echo "max freq:"
busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
busybox echo "min freq:"
busybox cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq
busybox echo "status of bacem-tweak:"
busybox cat /proc/sys/bacem/volt/cpu
busybox echo "voltage:"
busybox cat /sys/class/regulator/regulator.5/microvolts
busybox echo "note:" 
busybox echo "default voltage 832mhz = 1300000"
busybox echo "default voltage 312mhz = 1240000"
busybox echo "0mv is not in undervolt mode"
busybox echo "bacem-tweak from irfanbagus@xda" 
busybox echo "script by: savie@xda"
